name: Art request
description: Request Art for a project
title: "[Art] - "
labels: [documentation, art]
body:
- type: checkboxes
  attributes:
    label: Prerequisites
    description: Please answer the following questions for yourself before submitting a request.
    options:
    - label: I checked to make sure that this request has not already been filed
    - label: I'm reporting this information to the correct repository
    - label: I understand enough about this request to complete a comprehensive document
      required: true
- type: dropdown
  attributes:
    label: Project
    options:
        - Cryptoblades
        - Cryptoblades Kingdoms
        - Bazaar
        - CB Tracker
        - Bolstyr
        - Magicon
        - Other
  validations:
    required: true 
- type: textarea
  attributes:
    label: Describe the request and its requirements
    description: A clear and concise description of the request and its requirements. include all technical notes and finer details, not just an overview.
  validations:
    required: true
- type: textarea
  attributes:
    label: Is your art request related to an existing issue? Please describe.
    description: A clear and concise description of why it related to these others requests.
  validations:
    required: true
- type: textarea
  attributes:
    label: Is there anything stopping this feature from being completed?
    description: A list of any potential blockers for this feature with linked issues.
  validations:
    required: true
- type: textarea
  attributes:
    label: Potential Deadline
    description: A requested wishful date of completion and the reasoning for this date. This is not a set deadline that will be discussed from this issue.
  validations:
    required: true         
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or ideas you've considered.
  validations:
    required: true    
- type: textarea
  attributes:
    label: Banner / Sprite assets
    description: Please include any aspect ratios for assets required.
  validations:
    required: true      
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the art request here.
  validations:
    required: false