name: 'Bug report'
description: 'File a bug/issue'
title: "[BUG] -"
labels: [bug]
body:
- type: checkboxes
  attributes:
    label: Prerequisites
    description: Please answer the following questions for yourself before submitting an issue.
    options:
    - label: I have refreshed the chain and am still experiencing the bug
    - label: I have confirmed I am on the correct chain
    - label: I checked the documentation and found no answer
    - label: I checked to make sure that this issue has not already been filed
    - label: I'm reporting the issue to the correct repository
      required: true
- type: textarea
  attributes:
    label: Contact Details
    description: Any contact details for the finder of the bug should more information be required (Discord preferred).
  validations:
    required: false
- type: textarea
  attributes:
    label: What does this bug relate to
    value: |
        - Design Issues:
        - Missing Features:
        - Incorrect Data:
        - None of the above:
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Current behavior
    description: A clear and concise description of what actually happened.
  validations:
    required: true    
- type: textarea
  attributes:
    label: To Reproduce
    description: |
      Steps to reproduce the behaviour:
        - When on x page
        - Given x button is pressed
        - Then error x should be present
  validations:
    required: true
- type: textarea
  attributes:
    label: Device
    value: |
        - PC:
        - Mobile:
        - Other:
  validations:
    required: true  
- type: textarea
  attributes:
    label: Browser
    value: |
        - Chrome:
        - Safari:
        - Metamask:
        - Kiwi:
        - Firefox:
        - Brave:
        - Edge:
        - Other:
  validations:
    required: true        
- type: textarea
  attributes:
    label: Additional Context
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
