name: Feature request
about: Suggest an idea for this project
title: "[Feature] - "
labels: documentation, enhancement
body:
- type: checkboxes
  attributes:
    label: Prerequisites
    description: Please answer the following questions for yourself before submitting an issue.
    options:
    - label: I checked to make sure that this feature has not already been filed
    - label: I'm reporting this information to the correct repository
    - label: I understand enough about this issue to complete a comprehensive document
      required: true
- type: textarea
  attributes:
    label: Describe the feature and its requirements
    description: A clear and concise description of the feature and its requirements. include all technical notes and finer details, not just an overview.
  validations:
    required: true
- type: textarea
  attributes:
    label: Is your feature request related to an existing issue? Please describe.
    description: A clear and concise description of why it related to these issues.
  validations:
    required: true
- type: textarea
  attributes:
    label: Is there anything stopping this feature being completed?
    description: A list of any potential blockers for this feature with linked issues.
  validations:
    required: true
 - type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false